language: php
php:
- '7.0.2'
- '5.6'
- '5.5'
before_script:
- pear install --alldeps pear/PHP_CodeSniffer
- phpenv rehash
script:
- php -d error_reporting=E_ALL & ~E_WARNING
- phpcs --extensions=php -p --standard=PSR2 ./
